Mirrored action on Editor for sharing Content (and improving Analytics)
ministryofjustice/fb-runner pull request #1018
Opened 2022-09-07 13:38 UTC by stevenburnell-moj

- Add conversion adaptor to allow GovUK styled `<table>`
- Add fix for broken `<blockquote>` markdown -> html
- Add conversion adaptor to emulate GovSpeak `$CTA` elements.

All can be seen here:
<img width="690" alt="Screenshot 2022-09-07 at 14 35 36" src="https://user-images.githubusercontent.com/76942244/188892110-7f92a100-32bf-4bf3-bc3a-dbf11795b7ae.png">

For more information, see https://github.com/ministryofjustice/fb-editor/pull/1738

2022-09-12 15:13 UTC, chrispymm requested changes

2022-09-12 15:13 UTC, chrispymm commented on .circleci/config.yml
> +#            - deploy_to_live_production
👆what he said!

2022-09-12 17:39 UTC, stevenburnell-moj commented on .circleci/config.yml
> +#            - deploy_to_live_production
Damn it! Knew I'd forget that. Should now be gone, even history... erased from existence :-)

2022-09-13 08:50 UTC, chrispymm approved these changes

2022-09-13 08:51 UTC, merged